### ISSUE TITLE
Why `EnsureDeleted()`?

### ISSUE THREAD

**Issue by AngryCookie42** [aivascu/EntityFrameworkCore.AutoFixture#1]
Why exactly do we need to call EnsureDeleted?
I can, somewhat understand why we need EnsureCreated, but why exactly do we need to call EnsureDeleted? It seems to work without calling this method.

Would it possible to include these two methods in AutoFixutre somehow?

**Comment by aivascu** [comment]
Thank you for reaching out about this.
You are correct, I have to admit that the tests were written in a bit of a rush to put out the package.
In the context of the tests present in the tests and the `readme`, the `EnsureDeleted()` call is not necessary, since by default the library uses in memory databases.
Once the test ends and the context goes out of scope, the instances are disposed and the memory allocation is freed.
It would however make sense to keep the `EnsureDeleted()` call, if you would inject a `SqliteConnection` instance, into the `Fixture`, that has a connection string pointing to a file (e.g. `Data Source=testdatabase.sqlite`) rather than an in-memory database .
In this case the database file might not be cleaned, after the test has run and might even cause problems on subsequent test runs.
I will update/add more tests and the readme to better exemplify the usage of the library.

**Comment by aivascu** [comment]
Fixed in #2
