### ISSUE TITLE
Configire InMemoryOptionBuilder

### ISSUE THREAD

**Issue by yemo1** [aivascu/EntityFrameworkCore.AutoFixture#110]
Hi @aivascu,
How possible is it to suppress database transaction warning using this library.
I'm trying to configure DbContextOptions like below.

```cs
ConfigureWarnings(x => x.Ignore(InMemoryEventId.TransactionIgnoredWarning)
```

I can't see any property to achieve this on the InMemoryContextCustomization

Could you help with this please?

**Comment by aivascu** [comment]
Hi @yemo1,
The implementation currently doesn't allow the options to be configured by hand. At the time I didn't really see the value of it.
I think it might be possible to add the options builder as a property for the customization.
I'll check it out and see if I can manage to release a new version in a couple days.

**Comment by aivascu** [comment]
@yemo1 I think I have a working design for the feature you requested, and a couple more changes. Basically it ended up as a straight redesign since I also needed some new features, and I wanted to make room for other database providers as requested in the longstanding #101 . Oh and I made most of the default configurations fit 80% of the use cases.

Since there are so many changes I guess this will be the v2.0 of this package. I'll do my best to publish it on the weekend, but it might take one more week since I want to test it and document it properly before publishing. The changes are available in the [redesign](https://github.com/aivascu/EntityFrameworkCore.AutoFixture/tree/redesign) branch, if you want to borrow some stuff before release.

Here's a snipped of how the draft API looks like.

```cs
[Fact]
public void CanCreateContext()
{
    var fixture = new Fixture().Customize(
        new InMemoryCustomization
        {
            DatabaseName = "MyDb", // Default is going to be "TestDatabase"
            UseUniqueNames = true, // Enabled by default
            Configure = x => x
                .EnableServiceProviderCaching(false)
                .ConfigureWarnings(InMemoryEventId.TransactionIgnoredWarning), // null by default
            ConfigureProvider = x => x.EnableNullChecks(true), // null by default
            OmitDbSets = true, // Enabled by default
            OnCreate = OnCreateAction.Migrate // By default it is OnCreateAction.EnsureCreated
        });

    var context = fixture.Create<TestDbContext>();
}
```

**Comment by yemo1** [comment]
@aivascu , brilliant and thanks for the good work.
I'll look through the redesign branch before the final release.

**Comment by aivascu** [comment]
@yemo1 the version containing the API above is now available as a preview package [EntityFrameworkCore.AutoFixture v2.0.0-preview0002](https://www.nuget.org/packages/EntityFrameworkCore.AutoFixture/2.0.0-preview0002). The full version will release in the following days.
